# -*- coding: utf-8 -*-
"""Textos de interfaz y metadatos del sitio (ES / EN). El contenido largo de los casos vive en content/*/*.md"""

EMAIL = "alonsocantug@gmail.com"
LINKEDIN = "https://www.linkedin.com/in/alonso-cantug/"
BEHANCE = "https://www.behance.net/alonsocantu"

ROUTES = {
    "home":      {"es": "",                       "en": ""},
    "projects":  {"es": "proyectos/",             "en": "projects/"},
    "with-you":  {"es": "proyectos/with-you/",    "en": "projects/with-you/"},
    "firmia":    {"es": "proyectos/firmia/",      "en": "projects/firmia/"},
    "about":     {"es": "sobre-mi/",              "en": "about/"},
    "cv":        {"es": "cv/",                    "en": "cv/"},
}

# id de las secciones (se generan a partir de los títulos) para enlazar desde "Cómo trabajo"
ANCHORS = {
    "es": {"research": "investigacion", "design": "diseno", "test": "prueba-de-usabilidad-simulada", "system": "design-system"},
    "en": {"research": "research", "design": "design", "test": "usability-test", "system": "design-system"},
}

UI = {
 "es": {
  "skip": "Ir al contenido",
  "nav_projects": "Proyectos", "nav_about": "Sobre mí", "nav_cv": "CV",
  "lang_name": "English", "lang_code": "en", "lang_aria": "Read this site in English",
  "nav_label": "Principal",
  "home_title": "Alonso Cantú | Diseñador UX/UI y de producto en Monterrey",
  "home_desc": "Portafolio de Alonso Cantú, diseñador UX/UI y de producto en Monterrey, México. Casos de estudio de With You y Firmia, con investigación, prototipos, pruebas y sistemas de diseño.",
  "hero_role": "Diseñador UX/UI y de producto",
  "hero_lede": "Vengo del diseño industrial. Hoy diseño apps y plataformas: investigo, prototipo, pruebo y dejo documentado el sistema de diseño.",
  "hero_avail": "Monterrey, México. Disponible para trabajo remoto, híbrido, con reubicación o internacional.",
  "hero_cta1": "Leer el caso With You", "hero_cta2": "Descargar CV",
  "hero_dim": "App móvil de respiración guiada · 3 semanas · 2026",
  "hero_alt": "Tres pantallas de la app With You: inicio con selector de ánimo y botón Respira ahora, lista de ejercicios y progreso semanal",
  "work_h": "Trabajo seleccionado",
  "work_p": "Tres proyectos de portafolio, hechos de forma individual. Cada caso indica qué es real y qué es simulado.",
  "read_case": "Leer el caso",
  "see_behance": "Ver en Behance",
  "p_wy_title": "With You: app de respiración guiada para bajar la ansiedad",
  "p_wy_text": "De la investigación al sistema de diseño en tres semanas: personas, flujos, prototipo, una prueba de usabilidad y una auditoría de accesibilidad de mi propio kit.",
  "p_wy_tags": ["Proyecto de portafolio", "Individual", "2026"],
  "p_wy_facts": ["Investigación y prueba de usabilidad simuladas, indicadas como tales", "Prototipo navegable en Figma", "Sistema de diseño v1.1 con variables y 11 componentes"],
  "p_wy_alt": "Pantallas de alta fidelidad de With You: inicio, ejercicios y mi progreso",
  "p_fi_title": "Firmia: presupuestos de obra que el cliente revisa y firma",
  "p_fi_text": "Una landing, la vista previa interactiva de un presupuesto y un flujo móvil de 7 pantallas para iPhone 16. Es un concepto, sin cliente ni investigación con usuarios.",
  "p_fi_tags": ["Proyecto de portafolio", "Individual", "Concepto"],
  "p_fi_facts": ["Contraste medido contra WCAG 2.1 AA, con una falla encontrada", "Extensión móvil con prototipo", "Cifras de ejemplo, etiquetadas"],
  "p_fi_alt": "Hero de la landing de Firmia con titular, dos acciones y una tarjeta de presupuesto",
  "p_ds_title": "Dashboard para gestión de suscripciones",
  "p_ds_text": "Web app para ver 13+ servicios en 4 categorías desde un solo panel, con una biblioteca de componentes en Figma (Auto Layout y variables). El caso de estudio está en preparación.",
  "p_ds_tags": ["Proyecto de portafolio", "2026", "En preparación"],
  "how_h": "Cómo trabajo",
  "how_p": "Así lo hice en With You.",
  "how_link": "Ver en el caso",
  "how": [
    ("Investigo antes de dibujar", "Reviso fuentes y entrevisto para convertir hallazgos en decisiones. En With You las entrevistas fueron simuladas, y el caso lo dice.", "research"),
    ("Prototipo para decidir", "Wireframes de baja fidelidad para fijar la estructura antes del color, y un prototipo navegable en Figma.", "design"),
    ("Pruebo y cambio", "Una prueba con tres tareas mostró que “Historial” confundía. Pasó a llamarse “Mi progreso”.", "test"),
    ("Dejo un sistema", "Audité mi propio kit con WCAG 2.2 AA y lo rehice con variables y componentes con estados.", "system"),
  ],
  "about_short_h": "Sobre mí",
  "about_short": ["Estudié Diseño Industrial en la UANL y durante más de cuatro años diseñé, construí y coordiné proyectos de producto físico, de principio a fin y con clientes, proveedores y equipos de producción.",
                  "Ese proceso, entender qué necesita la gente, prototipar, validar e iterar, es el que hoy aplico a producto digital."],
  "about_more": "Más sobre mí",
  "contact_h": "Contacto",
  "contact_p": "Escríbeme si hay un equipo de producto digital donde pueda aportar esta visión de principio a fin.",
  "contact_email": "Correo", "contact_linkedin": "LinkedIn", "contact_behance": "Behance",
  "footer_note": "Todos los proyectos son de portafolio. Cada caso indica qué datos son de ejemplo o simulados.",
  "footer_rights": "© 2026 Alonso Cantú. Monterrey, México.",
  "projects_title": "Proyectos | Alonso Cantú",
  "projects_desc": "Casos de estudio de Alonso Cantú: With You (app de bienestar), Firmia (presupuestos de obra) y un dashboard de suscripciones.",
  "projects_h": "Proyectos",
  "projects_p": "Todos son proyectos de portafolio, hechos de forma individual. Empieza por With You, el caso más completo.",
  "case_in_page": "En esta página",
  "case_back": "Proyectos",
  "case_proto": "Abrir el prototipo en Figma",
  "case_other": "Otro caso",
  "table_label": "Tabla",
  "about_title": "Sobre mí | Alonso Cantú",
  "about_desc": "Diseñador industrial especializado en UX/UI. Trayectoria, formación y herramientas de Alonso Cantú.",
  "about_h": "Sobre mí",
  "about_lead": "Soy diseñador industrial y me especialicé en UX/UI con el certificado de TripleTen (2026).",
  "about_body": ["Durante más de cuatro años diseñé, construí y coordiné proyectos de producto físico de principio a fin: entender qué necesita cada cliente, prototipar antes de fabricar, validar con quienes lo usan e iterar. Es el mismo proceso que hoy aplico a producto digital.",
                 "Mi experiencia profesional es en producto físico, no digital. Mis proyectos digitales son de portafolio y lo indico en cada caso.",
                 "Busco integrarme a un equipo de producto digital donde aportar esa visión de principio a fin."],
  "path_h": "Trayectoria",
  "path": [
    ("Nov 2024 – hoy", "Consultor freelance en diseño y construcción", "Independiente, Monterrey", "Investigo las necesidades de cada cliente, prototipo y modelo en 3D antes de fabricar, y gestiono el proyecto de principio a fin con clientes, proveedores y equipos de producción."),
    ("May 2023 – Nov 2024", "Gerente de taller", "ART2PLAY, Mérida", "Analicé flujos de producción para detectar cuellos de botella y coordiné equipos multidisciplinarios para cumplir calidad y tiempos de entrega."),
    ("Mar 2021 – May 2023", "Diseñador de mobiliario freelance y voluntariado", "Monterrey", "Diseñé y fabriqué mobiliario a medida para clientes particulares, del concepto a la entrega."),
    ("Mar 2020 – Mar 2021", "Coordinador nacional de Fábrica Social", "TECHO México", "Coordiné proyectos de manufactura y construcción centrados en las necesidades de comunidades vulnerables."),
  ],
  "edu_h": "Formación",
  "edu": ["Certificado en UX/UI Design, TripleTen (2026)", "Licenciatura en Diseño Industrial, Universidad Autónoma de Nuevo León (2018)", "Certificado de inglés de 300 horas, Vancouver International College"],
  "tools_h": "Herramientas e idiomas",
  "tools": ["Figma, FigJam, Maze, SketchUp", "Herramientas de IA: ChatGPT y Claude", "Español nativo, inglés nivel profesional"],
  "cv_title": "CV | Alonso Cantú",
  "cv_desc": "Descarga el CV en español o el Resume en inglés de Alonso Cantú, diseñador UX/UI y de producto.",
  "cv_h": "CV",
  "cv_p": "Descarga mi CV en español o mi Resume en inglés. Son PDF de dos páginas.",
  "cv_cards": [("CV en español", "Alonso_Cantu_CV_ES.pdf", "es"), ("Resume in English", "Alonso_Cantu_Resume_EN.pdf", "en")],
  "download": "Descargar PDF",
  "nf_title": "Página no encontrada | Alonso Cantú",
 },
 "en": {
  "skip": "Skip to content",
  "nav_projects": "Projects", "nav_about": "About", "nav_cv": "Resume",
  "lang_name": "Español", "lang_code": "es", "lang_aria": "Leer este sitio en español",
  "nav_label": "Main",
  "home_title": "Alonso Cantú | UX/UI and Product Designer in Monterrey",
  "home_desc": "Portfolio of Alonso Cantú, UX/UI and product designer in Monterrey, Mexico. Case studies for With You and Firmia, with research, prototypes, testing and design systems.",
  "hero_role": "UX/UI and Product Designer",
  "hero_lede": "I come from industrial design. Today I design apps and platforms: I research, prototype, test and document the design system.",
  "hero_avail": "Monterrey, Mexico. Open to remote, hybrid, relocation or international roles.",
  "hero_cta1": "Read the With You case study", "hero_cta2": "Download resume",
  "hero_dim": "Guided-breathing mobile app · 3 weeks · 2026",
  "hero_alt": "Three screens of the With You app: home with a mood selector and a Breathe now button, exercise list and weekly progress",
  "work_h": "Selected work",
  "work_p": "Three portfolio projects, each done on my own. Every case says what is real and what is simulated.",
  "read_case": "Read the case study",
  "see_behance": "View on Behance",
  "p_wy_title": "With You: a guided-breathing app to lower anxiety",
  "p_wy_text": "From research to design system in three weeks: personas, flows, a prototype, a usability test and an accessibility audit of my own kit.",
  "p_wy_tags": ["Portfolio project", "Individual", "2026"],
  "p_wy_facts": ["Simulated research and usability test, labeled as such", "Interactive prototype in Figma", "Design system v1.1 with variables and 11 components"],
  "p_wy_alt": "High-fidelity screens of With You: home, exercises and my progress",
  "p_fi_title": "Firmia: construction quotes the client reviews and signs",
  "p_fi_text": "A landing page, an interactive quote preview and a 7-screen mobile flow for iPhone 16. It is a concept, with no client and no user research.",
  "p_fi_tags": ["Portfolio project", "Individual", "Concept"],
  "p_fi_facts": ["Contrast measured against WCAG 2.1 AA, with one failure found", "Mobile extension with a prototype", "Example figures, labeled"],
  "p_fi_alt": "Firmia landing hero with a headline, two actions and a quote card",
  "p_ds_title": "Subscription management dashboard",
  "p_ds_text": "A web app to see 13+ services across 4 categories in one dashboard, with a component library in Figma (Auto Layout and variables). The case study is in progress.",
  "p_ds_tags": ["Portfolio project", "2026", "In progress"],
  "how_h": "How I work",
  "how_p": "This is how I did it on With You.",
  "how_link": "See it in the case",
  "how": [
    ("Research before drawing", "I review sources and interview people to turn findings into decisions. On With You the interviews were simulated, and the case says so.", "research"),
    ("Prototype to decide", "Low-fidelity wireframes to set the structure before color, and an interactive prototype in Figma.", "design"),
    ("Test and change", "A three-task test showed that “Historial” was confusing. It became “Mi progreso”.", "test"),
    ("Leave a system behind", "I audited my own kit against WCAG 2.2 AA and rebuilt it with variables and components with states.", "system"),
  ],
  "about_short_h": "About me",
  "about_short": ["I studied Industrial Design at UANL and for more than four years I designed, built and coordinated physical product projects end to end, working with clients, suppliers and production teams.",
                  "That process, understanding what people need, prototyping, validating and iterating, is what I now apply to digital products."],
  "about_more": "More about me",
  "contact_h": "Contact",
  "contact_p": "Write to me if there is a digital product team where I can bring this end-to-end perspective.",
  "contact_email": "Email", "contact_linkedin": "LinkedIn", "contact_behance": "Behance",
  "footer_note": "All projects are portfolio projects. Each case says which data is example or simulated.",
  "footer_rights": "© 2026 Alonso Cantú. Monterrey, Mexico.",
  "projects_title": "Projects | Alonso Cantú",
  "projects_desc": "Case studies by Alonso Cantú: With You (wellbeing app), Firmia (construction quotes) and a subscription dashboard.",
  "projects_h": "Projects",
  "projects_p": "All of them are portfolio projects, done on my own. Start with With You, the most complete case.",
  "case_in_page": "On this page",
  "case_back": "Projects",
  "case_proto": "Open the prototype in Figma",
  "case_other": "Another case",
  "table_label": "Table",
  "about_title": "About | Alonso Cantú",
  "about_desc": "Industrial designer specialized in UX/UI. Background, education and tools of Alonso Cantú.",
  "about_h": "About me",
  "about_lead": "I am an industrial designer who specialized in UX/UI through the TripleTen certificate (2026).",
  "about_body": ["For more than four years I designed, built and coordinated physical product projects end to end: understanding what each client needs, prototyping before manufacturing, validating with the people who use the product, and iterating. It is the same process I now apply to digital products.",
                 "My professional experience is in physical products, not digital ones. My digital projects are portfolio projects and I say so in each case.",
                 "I am looking to join a digital product team where I can bring that end-to-end perspective."],
  "path_h": "Background",
  "path": [
    ("Nov 2024 – present", "Freelance design and construction consultant", "Self-employed, Monterrey", "I research each client's needs, prototype and model in 3D before manufacturing, and manage the project end to end with clients, suppliers and production teams."),
    ("May 2023 – Nov 2024", "Workshop manager", "ART2PLAY, Mérida", "I analyzed production workflows to find bottlenecks and coordinated cross-functional teams to meet quality standards and delivery times."),
    ("Mar 2021 – May 2023", "Freelance furniture designer and volunteer", "Monterrey", "I designed and built custom furniture for private clients, from concept to delivery."),
    ("Mar 2020 – Mar 2021", "National Social Factory coordinator", "TECHO México", "I coordinated manufacturing and construction projects centered on the needs of vulnerable communities."),
  ],
  "edu_h": "Education",
  "edu": ["UX/UI Design Certificate, TripleTen (2026)", "Bachelor's degree in Industrial Design, Universidad Autónoma de Nuevo León (2018)", "300-hour English certificate, Vancouver International College"],
  "tools_h": "Tools and languages",
  "tools": ["Figma, FigJam, Maze, SketchUp", "AI tools: ChatGPT and Claude", "Spanish native, English professional proficiency"],
  "cv_title": "Resume | Alonso Cantú",
  "cv_desc": "Download Alonso Cantú's resume in English or his CV in Spanish. UX/UI and product designer.",
  "cv_h": "Resume",
  "cv_p": "Download my resume in English or my CV in Spanish. Both are two-page PDFs.",
  "cv_cards": [("Resume in English", "Alonso_Cantu_Resume_EN.pdf", "en"), ("CV en español", "Alonso_Cantu_CV_ES.pdf", "es")],
  "download": "Download PDF",
  "nf_title": "Page not found | Alonso Cantú",
 },
}
